language: csharp
dist: trusty
services:
  - postgresql
  - mysql
  - docker
env:
  global:
    - PGPASSWORD: 
    - MYSQL_PWD:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
sudo: required
mono: none
dotnet: 1.0.1
os:
  - linux
  # - osx CoreCLR tests time out too frequently on OSX to be useful.
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
  - docker run --name sqlserver -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password12!' -p 1433:1433 -d microsoft/mssql-server-linux:latest
  # - chmod +x build.sh
before_script:
  - psql -c 'create database my_database;' -U postgres
  - mysql -e 'CREATE DATABASE my_database;' --user=root
script:
  - dotnet restore
  - dotnet build ./src/Evolve/Evolve.csproj -c Release -f netcoreapp1.0
  - dotnet build ./test/Evolve.Core.Test/Evolve.Core.Test.csproj -c Release -f netcoreapp1.0
  - dotnet build ./test/Evolve.Core.Test.Driver/Evolve.Core.Test.Driver.csproj -c Release -f netcoreapp1.0
  - dotnet build ./test/Evolve.Core.Test.Resources.SupportedDrivers/Evolve.Core.Test.Resources.SupportedDrivers.csproj -c Release -f netcoreapp1.0
  - dotnet test ./test/Evolve.Core.Test/Evolve.Core.Test.csproj -c Release -f netcoreapp1.0
  - dotnet test ./test/Evolve.Core.Test.Driver/Evolve.Core.Test.Driver.csproj -c Release -f netcoreapp1.0
