language: csharp
dist: trusty
services:
  - docker
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
sudo: required
mono: 5.8.0
dotnet: 2.1.301
os: linux
before_script:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys B02C46DF417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.0.4
  - chmod a+x ./build.sh
script:
  - ./build.sh
