language: csharp
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
sudo: required
mono: none
dotnet: 1.0.1
os:
  - linux
  # - osx CoreCLR tests time out too frequently on OSX to be useful.
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
  # - chmod +x build.sh
script:
  - dotnet restore -r ubuntu.14.04-x64
  - dotnet build ./src/Evolve/Evolve.csproj -c Release -f netstandard1.3 -r ubuntu.14.04-x64
